# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{langusta}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jan Szumiec"]
  s.date = %q{2011-04-10}
  s.default_executable = %q{langusta}
  s.description = %q{Highly accurate language detection library, uses naive bayesian filter.}
  s.email = %q{jan.szumiec@gmail.com}
  s.executables = ["langusta"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/langusta",
    "data/messages.properties",
    "data/uppercase.bin",
    "langusta.gemspec",
    "lib/langusta.rb",
    "lib/langusta/command.rb",
    "lib/langusta/detector.rb",
    "lib/langusta/detector_factory.rb",
    "lib/langusta/java_property_reader.rb",
    "lib/langusta/lang_profile.rb",
    "lib/langusta/language.rb",
    "lib/langusta/language_detection_facade.rb",
    "lib/langusta/n_gram.rb",
    "lib/langusta/regex_helper.rb",
    "lib/langusta/tag_extractor.rb",
    "lib/langusta/ucs2_string.rb",
    "lib/langusta/unicode_block.rb",
    "profiles/af",
    "profiles/ar",
    "profiles/bg",
    "profiles/bn",
    "profiles/cs",
    "profiles/da",
    "profiles/de",
    "profiles/el",
    "profiles/en",
    "profiles/es",
    "profiles/fa",
    "profiles/fi",
    "profiles/fr",
    "profiles/gu",
    "profiles/he",
    "profiles/hi",
    "profiles/hr",
    "profiles/hu",
    "profiles/id",
    "profiles/it",
    "profiles/ja",
    "profiles/kn",
    "profiles/ko",
    "profiles/mk",
    "profiles/ml",
    "profiles/mr",
    "profiles/ne",
    "profiles/nl",
    "profiles/no",
    "profiles/pa",
    "profiles/pl",
    "profiles/pt",
    "profiles/ro",
    "profiles/ru",
    "profiles/sk",
    "profiles/so",
    "profiles/sq",
    "profiles/sv",
    "profiles/sw",
    "profiles/ta",
    "profiles/te",
    "profiles/th",
    "profiles/tl",
    "profiles/tr",
    "profiles/uk",
    "profiles/ur",
    "profiles/vi",
    "profiles/zh-cn",
    "profiles/zh-tw",
    "test/helper.rb",
    "test/quality/test_falsified.rb",
    "test/test_command.rb",
    "test/test_data/af",
    "test/test_data/ar",
    "test/test_data/bg",
    "test/test_data/bn",
    "test/test_data/cs",
    "test/test_data/da",
    "test/test_data/de",
    "test/test_data/el",
    "test/test_data/en",
    "test/test_data/es",
    "test/test_data/fa",
    "test/test_data/fi",
    "test/test_data/fr",
    "test/test_data/gu",
    "test/test_data/he",
    "test/test_data/hi",
    "test/test_data/hr",
    "test/test_data/hu",
    "test/test_data/id",
    "test/test_data/it",
    "test/test_data/ja",
    "test/test_data/kn",
    "test/test_data/ko",
    "test/test_data/mk",
    "test/test_data/ml",
    "test/test_data/mr",
    "test/test_data/ne",
    "test/test_data/nl",
    "test/test_data/no",
    "test/test_data/pa",
    "test/test_data/pl",
    "test/test_data/pt",
    "test/test_data/ro",
    "test/test_data/ru",
    "test/test_data/sk",
    "test/test_data/so",
    "test/test_data/sq",
    "test/test_data/sv",
    "test/test_data/sw",
    "test/test_data/ta",
    "test/test_data/te",
    "test/test_data/th",
    "test/test_data/tl",
    "test/test_data/tr",
    "test/test_data/uk",
    "test/test_data/ur",
    "test/test_data/vi",
    "test/test_data/zh-tw",
    "test/test_detector.rb",
    "test/test_detector_factory.rb",
    "test/test_java_property_reader.rb",
    "test/test_lang_profile.rb",
    "test/test_language.rb",
    "test/test_language_detection_facade.rb",
    "test/test_langusta.rb",
    "test/test_n_gram.rb",
    "test/test_tag_extractor.rb",
    "test/test_ucs2_string.rb",
    "test/test_unicode_block.rb"
  ]
  s.homepage = %q{http://github.com/jasiek/langusta}
  s.licenses = ["Apache 2.0"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.1}
  s.summary = %q{Language detection library based on http://code.google.com/p/language-detection/.}
  s.test_files = [
    "test/helper.rb",
    "test/quality/test_falsified.rb",
    "test/test_command.rb",
    "test/test_detector.rb",
    "test/test_detector_factory.rb",
    "test/test_java_property_reader.rb",
    "test/test_lang_profile.rb",
    "test/test_language.rb",
    "test/test_language_detection_facade.rb",
    "test/test_langusta.rb",
    "test/test_n_gram.rb",
    "test/test_tag_extractor.rb",
    "test/test_ucs2_string.rb",
    "test/test_unicode_block.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<oniguruma>, ["= 1.1.0"])
      s.add_runtime_dependency(%q<yajl-ruby>, ["= 0.8.2"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<mocha>, [">= 0"])
      s.add_development_dependency(%q<ruby-debug>, [">= 0"])
    else
      s.add_dependency(%q<oniguruma>, ["= 1.1.0"])
      s.add_dependency(%q<yajl-ruby>, ["= 0.8.2"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<mocha>, [">= 0"])
      s.add_dependency(%q<ruby-debug>, [">= 0"])
    end
  else
    s.add_dependency(%q<oniguruma>, ["= 1.1.0"])
    s.add_dependency(%q<yajl-ruby>, ["= 0.8.2"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<mocha>, [">= 0"])
    s.add_dependency(%q<ruby-debug>, [">= 0"])
  end
end

